name: AWS OIDC Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository=${{ github.repository }}"
          echo "Ref=${{ github.ref }}"
          echo "Actor=${{ github.actor }}"

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::917675236489:role/s3-read
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: List S3 Buckets
        run: aws s3 ls

        
